### ISSUE TITLE
Does not run on newer versions of Julia

### ISSUE THREAD

**Issue by Microbiology** [Microbiology/ccontigs#1]
Some of the Julia syntax got updated recently and now the `ccontigs` script does not work. Right now, people are going to have to run `ccontigs` on an old version. Preferably `4.5`.

I'll get around to updating it, but I'll admit this is low on my priority list right now.

**Comment by osnattirosh** [comment]
any chance for an update on the ccontigs script? I'll deeply appreciate it

**Comment by Microbiology** [comment]
Thanks for asking. The fact that there is interest in it let's me know I should prioritize an update. It's been low on my list but it's getting to be time that I really should go through and update it. I might not get to it right away, but I'll fix it when I get a chance. Probably in a week or so.

**Comment by osnattirosh** [comment]
Thanks! I’ll look forward to it!
